/**
 * post-build.js — runs automatically after `vite build`
 *
 * 1. Reads dist/index.html
 * 2. Computes SHA-256 hash
 * 3. Generates dist/index.php — PHP security wrapper with:
 *      - HTTP security headers set server-side
 *      - SHA-256 integrity check of app.html on every request
 *      - Base64-encoded clean backup served if tampering is detected
 * 4. Renames dist/index.html → dist/app.html
 *    (malware scanners target "index.html" by name — it won't exist)
 */

import { readFileSync, writeFileSync, renameSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { resolve } from 'node:path'

const dist     = resolve(process.cwd(), 'dist')
const htmlPath = resolve(dist, 'index.html')
const phpPath  = resolve(dist, 'index.php')
const appPath  = resolve(dist, 'app.html')

// Read the built HTML
const html    = readFileSync(htmlPath, 'utf8').trimEnd()
const hash    = createHash('sha256').update(html).digest('hex')
const b64html = Buffer.from(html, 'utf8').toString('base64')

const CSP = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com",
  "img-src 'self' data: https: blob:",
  "connect-src 'self' https://revtrailmed.com https://fonts.googleapis.com",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
].join('; ')

// Generate index.php
// Uses base64 for the embedded backup — avoids any heredoc/quote escaping issues
const php = `<?php
// RevTrailMed - Security hardened entry point
// Auto-generated by scripts/post-build.js - do not edit manually

// Security headers
header('Content-Security-Policy: ${CSP}');
header('X-Frame-Options: DENY');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: strict-origin-when-cross-origin');
header('Cache-Control: no-cache, no-store, must-revalidate');
header('Content-Type: text/html; charset=UTF-8');

// Known-good SHA-256 hash of app.html (stamped at build time)
$expected = '${hash}';

// Clean backup embedded at build time (base64-encoded)
$backup = base64_decode('${b64html}');

$shell = __DIR__ . '/app.html';

if (!file_exists($shell)) {
    echo $backup;
    exit;
}

$content = file_get_contents($shell);
$actual  = hash('sha256', trim($content));

if ($actual !== $expected) {
    error_log('[RevTrailMed] SECURITY: app.html tampered at ' . date('c'));
    echo $backup;
    exit;
}

echo $content;
`

writeFileSync(phpPath, php, 'utf8')
renameSync(htmlPath, appPath)

console.log('\n  Security wrapper generated')
console.log('  app.html SHA-256:', hash)
console.log('  index.php written (base64 backup embedded)')
console.log('  index.html renamed to app.html\n')
