/**
 * post-build.js
 * Runs automatically after `vite build`.
 *
 * What it does:
 *  1. Reads the Vite-generated dist/index.html
 *  2. Computes its SHA-256 hash
 *  3. Generates dist/index.php — a PHP security wrapper that:
 *       - Sets all HTTP security headers (CSP, X-Frame-Options, etc.)
 *       - Verifies app.html integrity on every request via SHA-256
 *       - Falls back to an embedded clean backup if tampering is detected
 *  4. Renames dist/index.html → dist/app.html
 *     (automated malware scanners target "index.html" by name — it won't exist)
 */

import { readFileSync, writeFileSync, renameSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { resolve } from 'node:path'

const dist     = resolve(process.cwd(), 'dist')
const htmlPath = resolve(dist, 'index.html')
const phpPath  = resolve(dist, 'index.php')
const appPath  = resolve(dist, 'app.html')

// ── Read the built HTML ──────────────────────────────────────────
const html = readFileSync(htmlPath, 'utf8').trimEnd()
const hash = createHash('sha256').update(html).digest('hex')

// ── Content Security Policy ──────────────────────────────────────
const CSP = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com",
  "img-src 'self' data: https: blob:",
  "connect-src 'self' https://revtrailmed.com https://fonts.googleapis.com",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "upgrade-insecure-requests",
].join('; ')

// ── Generate index.php ───────────────────────────────────────────
// Uses PHP nowdoc (<<<'DELIM') so the HTML backup needs zero escaping.
// The delimiter REVTRAILMED_SHELL is unique enough to never appear in built HTML.
const php = `<?php
/**
 * RevTrailMed — Security-hardened entry point.
 * Auto-generated by scripts/post-build.js on every build.
 * Do NOT edit manually — run \`npm run build\` to regenerate.
 */

// ── Security headers (set here so they work even if .htaccess is disabled) ──
header('Content-Security-Policy: ${CSP}');
header('X-Frame-Options: DENY');
header('X-Content-Type-Options: nosniff');
header('X-XSS-Protection: 1; mode=block');
header('Referrer-Policy: strict-origin-when-cross-origin');
header('Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()');
header('Cache-Control: no-cache, no-store, must-revalidate');
header('Pragma: no-cache');
header('Content-Type: text/html; charset=UTF-8');

// ── Known-good SHA-256 hash of app.html (set at build time) ─────
$expected_hash = '${hash}';

// ── Clean app shell embedded at build time ───────────────────────
// Used as fallback if app.html is missing or has been tampered with.
$clean_html = <<<'REVTRAILMED_SHELL'
${html}
REVTRAILMED_SHELL;

// ── Integrity check ──────────────────────────────────────────────
$shell_path = __DIR__ . '/app.html';

if (!file_exists($shell_path)) {
    // Shell file is missing — serve embedded backup silently
    echo $clean_html;
    exit;
}

$content     = file_get_contents($shell_path);
$actual_hash = hash('sha256', trim($content));

if ($actual_hash !== $expected_hash) {
    // Hash mismatch: app.html has been tampered with.
    // Log the incident and serve the embedded clean backup.
    error_log(
        '[RevTrailMed SECURITY] Integrity failure at ' . date('c') . ' — ' .
        'expected=' . $expected_hash . ' got=' . $actual_hash
    );
    echo $clean_html;
    exit;
}

// File is clean — serve it normally.
echo $content;
`

// ── Write files ──────────────────────────────────────────────────
writeFileSync(phpPath, php, 'utf8')
renameSync(htmlPath, appPath)

console.log('\n✓ Security wrapper generated')
console.log('  app.html SHA-256 :', hash)
console.log('  index.php        : written with embedded backup + integrity check')
console.log('  index.html       : renamed → app.html\n')
